name: YouTube Transcription

on:
  issues:
    types: [opened, edited]

jobs:
  transcribe:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, '[TRANSCRIBE]')
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm install
          
      - name: Process Video
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node src/github-action.js
