name: YouTube Transcription

on:
  issues:
    types: [opened, edited]

jobs:
  transcribe:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, '[TRANSCRIBE]')
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Process Video
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./src/github-action.js')
            await script.run()
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
